# 安裝tabula-py 套件

### 1. 網路上給的方法
在終端機上面打這行

pip install tabula-py

### 2. 從終端機直接打這一行（可行）

conda install -c conda-forge tabula-py
#### 即可安裝tabula-py 套件

## 範例一

記得檔案要丟在，同一個目錄底下

In [3]:
import tabula

In [4]:
# Read pdf into DataFrame
df = tabula.read_pdf( "data.pdf" )
df

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

## 範例二（表）

In [14]:
df_table = tabula.read_pdf( "selection01.pdf" )
df_table

,Number of species in genus,141,4,3,10,1,1.1,17,4.1,4.2,2,4 3,3.1,1.2,2.1,1.3,1.4,1.5,9
0,Gram reaction,+/v/−,+,+,+,+,−,+/−,+,+,+,v +,+,+,+,+,+,+,+
1,Predominant cell shape:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Rods,+,+,+,+,+,+,+,+,+,+,+,+,+,+,NaN,+,+,+
3,Cocci,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+,NaN,+,NaN,NaN,NaN,+,NaN,NaN,NaN
4,Mean cell width:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,<0.5 mm,NaN,NaN,+,NaN,NaN,+,NaN,+,NaN,NaN,1. Bacillus,NaN,+,NaN,NaN,+,NaN,+
6,0.5–1.0 mm,+,+,+,+,+,NaN,+,+,+,+,+,+,NaN,+,NaN,NaN,NaN,+
7,1.0 or >1.0 mm,+,+,NaN,+,NaN,NaN,+,NaN,+,NaN,+,NaN,NaN,NaN,NaN,+,NaN,+
8,Motility,+/−,+,+,+/−,NaN,NaN,+/−,+,+/−,NaN,2. Alk+a/l−ibacllus+,+,+,+,−,+,+,+
9,Spore formation,+/−,+,+,+,+,+,+,+,+,−,+ −,+,+,+,−,+,+,+
10,Spore shape:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Ellipsoidal,+,NaN,+,+,NaN,NaN,+,+,+,NaN,3. Amp+hibacillus,+,+,NaN,NaN,NaN,+,+
12,Cylindrical,+,NaN,NaN,+,NaN,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Spherical,+,+,NaN,+,+,+,NaN,+,+,NaN,+,NaN,+,+,NaN,+,NaN,+
14,Oxygen requirements:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4. Anoxybacillus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Aerobes,+,+,+,+,+,+,+,+,+,+,+ +,+,+,+,+,+,+,+
16,Facultative anaerobes,+,−,+,+,−,NaN,+,+,−,+,− −,+,+,−,−,NaN,−,+
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5. Cerasibacillus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Strict anaerobes,+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Growth in media with added NaCl:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0%,+,−,NaN,+,+,−,+,v,−,+,6. Filob−acillus v,+,+,−,+,−,−,v
21,5%,+,+,+,+,+,+,+,+,+,+,+ +,+,+,+,NaN,+,+,+
22,10%,+,+,NaN,−,−,+,+,+,+,+,+ +,+,+,+,NaN,+,+,+
23,20%,+,+,NaN,NaN,NaN,+,NaN,+,+,+,7. Geob+acillus +,+,+,−,NaN,+,+,+
24,Growth at:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,10 °C,+,NaN,NaN,NaN,NaN,NaN,NaN,+,+,+,+,+,NaN,NaN,NaN,NaN,NaN,+
26,20 °C,+,+,+,NaN,NaN,NaN,NaN,+,+,+,8. Gra+cilibacillus,+,NaN,+,NaN,+,+,+
27,30 °C,+,+,+,+,+,+,NaN,+,+,+,+ +,+,+,+,NaN,+,+,+
28,40 °C,+,+,+,+,+,NaN,+,+,+,+,+,+,NaN,+,NaN,+,+,+
29,50 °C,+,+,+,+,+,NaN,+,+,NaN,NaN,9. Halobacillus,NaN,NaN,NaN,+,NaN,NaN,+
30,60 °C,+,NaN,−,+,+,NaN,+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+,NaN,NaN,NaN
31,Growth at pH:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,5,+,−,NaN,+,NaN,NaN,NaN,+,NaN,NaN,10. Ha+lolactibacillus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,6,+,−,NaN,+,NaN,+,+,+,+,+,+,NaN,+,+,NaN,+,+,+
34,7,+,+,+,+,NaN,+,+,+,+,+,+ +,+,+,+,+,+,+,+
35,8,+,+,+,+,+,+,+,+,+,+,11. Len+tibacillus,+,+,NaN,NaN,+,+,+
36,9,+,+,+,+,+,NaN,NaN,+,+,+,+,+,+,NaN,NaN,+,+,+
37,10,+,+,+,+,+,NaN,NaN,+,NaN,+,+12. Marinococcus,+,NaN,NaN,NaN,NaN,+,NaN
38,Catalase,+/−,+,−,+/−,+,+,+/−,+,+,−,+ +,+,+,+,+,+,+,+
39,Oxidase,+/−,−,−,+/−,NaN,−,v,NaN,+,−,v −,v,NaN,+/−,+,+,−,+

## 範例三（圖）沒東西

In [15]:
tabula?

In [18]:
df2_table = tabula.read_pdf( "Bergey's.Manual.[Vol.3].The.Firmicutes.pdf", pages = 607 )
df2_table

   d-Ribose, d-xylose, d-glucose, d-fructose, d-mannose, maltose, sucrose, +
0   d-cellobiose, d-trehalose, d-mannitol, α-methy...
1   l-Arabinose, d-galactose, lactose, d-rhamnose (+)
2                                        Glycerol (w)
3                                       d-Arabinose v
4   Melibiose, d-raffinose, d-melezitose, adonitol...
5                                      myo-Inositol −
6                                Gas from gluconate −
7         Major fatty acid composition (% of total):c
8                                           C 0.412:0
9                                           C 5.214:0
10                                          C 0.415:0
11                                         C 32.016:0
12                                          C 3.116:1
13                                      C 19.316:1 ω7
14                                          C 6.918:0
15                         C 30.218:1 ω9 (oleic acid)
16                                          C 1.118:2
17                                          C 1.420:1